/**
 * "The perfect pictures guide" shown from the sell wizard's photo step.
 *
 * GENERATED by scripts/render-photo-guide.py — edit the PDF or the script,
 * not this file. The guide is a designed document (Albanian, with
 * reference photos) rendered as one JPEG strip per section, cut between
 * the section cards so no photo is split. Sizes are intrinsic pixels at
 * 2x, which is what next/image needs to reserve space.
 */
export interface PhotoGuideImage {
  src: string;
  width: number;
  height: number;
  alt: string;
}

export const PHOTO_GUIDE_TITLE = 'The perfect pictures guide';

export const PHOTO_GUIDE_IMAGES: PhotoGuideImage[] = [
  {
    src: '/guides/photo-guide-1.jpg',
    width: 1050,
    height: 3184,
    alt:
      "Section 1, the main photo: lay the item flat on a plain contrasting surface, centred, straight, evenly lit from the front, phone held at 90 degrees. Examples of good and bad main photos of a red shirt and a navy skirt.",
  },
  {
    src: '/guides/photo-guide-2.jpg',
    width: 1050,
    height: 1720,
    alt:
      "Section 2, add several photos: a bag shot from the front, back, side, bottom and close up. Iron and clean garments, upload up to 10 photos from every angle, and show any defects honestly so the item is verified faster.",
  },
  {
    src: '/guides/photo-guide-3.jpg',
    width: 1050,
    height: 1608,
    alt:
      "Section 3, label photos: photograph the hang tag clearly if the item still has one, and the inner labels too. Examples with a price tag, a brand tag and an inner care label.",
  },
  {
    src: '/guides/photo-guide-4.jpg',
    width: 1050,
    height: 988,
    alt:
      "Section 4, packaging: show the extras you will hand over, such as the dust bag, and for designer items the receipt and authenticity card if you have them.",
  },
];
