#!/usr/bin/env python3
"""
Render "The perfect pictures guide" PDF into the JPEG strips the sell wizard
shows (public/guides/photo-guide-N.jpg) and regenerate src/lib/photo-guide.ts.

    python3 -m venv .venv && .venv/bin/pip install pymupdf
    .venv/bin/python scripts/render-photo-guide.py "path/to/guide.pdf"

The guide is one tall page with a header and four section cards. The strips
are cut in the gaps *between* the cards (found from the page's drawn
rectangles), so no reference photo is ever split across two images. Rendered
at 2x (1050px wide) for retina, JPEG quality 82 — about 1 MB for the set,
loaded only when the dialog opens.

Edit ALT_TEXTS below if the sections change; they are the screen-reader
description of each strip, and the only English the guide carries.
"""
import os
import sys

try:
    import pymupdf
except ImportError:
    sys.exit("pymupdf is not installed: pip install pymupdf")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "public", "guides")
MANIFEST = os.path.join(ROOT, "src", "lib", "photo-guide.ts")
SCALE = 2
QUALITY = 82

ALT_TEXTS = [
    "Section 1, the main photo: lay the item flat on a plain contrasting surface, centred, straight, evenly lit from the front, phone held at 90 degrees. Examples of good and bad main photos of a red shirt and a navy skirt.",
    "Section 2, add several photos: a bag shot from the front, back, side, bottom and close up. Iron and clean garments, upload up to 10 photos from every angle, and show any defects honestly so the item is verified faster.",
    "Section 3, label photos: photograph the hang tag clearly if the item still has one, and the inner labels too. Examples with a price tag, a brand tag and an inner care label.",
    "Section 4, packaging: show the extras you will hand over, such as the dust bag, and for designer items the receipt and authenticity card if you have them.",
]


def card_bounds(page):
    """Top/bottom of each section card: the wide, tall drawn rectangles."""
    w = page.rect.width
    cards = set()
    for d in page.get_drawings():
        r = d["rect"]
        if r.width > w * 0.8 and 300 < r.height < page.rect.height * 0.9:
            cards.add((r.y0, r.y1))
    return sorted(cards)


def cut_points(page):
    """Cut halfway through each gap between consecutive cards."""
    cards = card_bounds(page)
    if len(cards) < 2:
        sys.exit(f"expected several section cards, found {len(cards)}")
    cuts, top = [], 0.0
    for (_, prev_bottom), (next_top, _) in zip(cards, cards[1:]):
        mid = (prev_bottom + next_top) / 2
        cuts.append((top, mid))
        top = mid
    cuts.append((top, page.rect.height))
    return cuts


def main(pdf_path):
    doc = pymupdf.open(pdf_path)
    if len(doc) != 1:
        sys.exit(f"expected a single tall page, got {len(doc)} pages")
    page = doc[0]
    cuts = cut_points(page)
    if len(cuts) != len(ALT_TEXTS):
        sys.exit(f"{len(cuts)} strips but {len(ALT_TEXTS)} alt texts — update ALT_TEXTS")

    os.makedirs(OUT_DIR, exist_ok=True)
    entries = []
    for i, (y0, y1) in enumerate(cuts, 1):
        clip = pymupdf.Rect(0, y0, page.rect.width, y1)
        pix = page.get_pixmap(matrix=pymupdf.Matrix(SCALE, SCALE), clip=clip, alpha=False)
        path = os.path.join(OUT_DIR, f"photo-guide-{i}.jpg")
        pix.save(path, jpg_quality=QUALITY)
        entries.append((f"/guides/photo-guide-{i}.jpg", pix.width, pix.height, ALT_TEXTS[i - 1]))
        print(f"{path}  {pix.width}x{pix.height}  {os.path.getsize(path) // 1024} KB")

    lines = [
        "/**",
        ' * "The perfect pictures guide" shown from the sell wizard\'s photo step.',
        " *",
        " * GENERATED by scripts/render-photo-guide.py — edit the PDF or the script,",
        " * not this file. The guide is a designed document (Albanian, with",
        " * reference photos) rendered as one JPEG strip per section, cut between",
        " * the section cards so no photo is split. Sizes are intrinsic pixels at",
        f" * {SCALE}x, which is what next/image needs to reserve space.",
        " */",
        "export interface PhotoGuideImage {",
        "  src: string;",
        "  width: number;",
        "  height: number;",
        "  alt: string;",
        "}",
        "",
        "export const PHOTO_GUIDE_TITLE = 'The perfect pictures guide';",
        "",
        "export const PHOTO_GUIDE_IMAGES: PhotoGuideImage[] = [",
    ]
    for src, w, h, alt in entries:
        alt_js = alt.replace("\\", "\\\\").replace('"', '\\"')
        lines += [
            "  {",
            f"    src: '{src}',",
            f"    width: {w},",
            f"    height: {h},",
            "    alt:",
            f'      "{alt_js}",',
            "  },",
        ]
    lines += ["];", ""]
    with open(MANIFEST, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {MANIFEST}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
